### ISSUE TITLE
Error calling BaseDirectoryForDynamicLoadNativeLibrary

### ISSUE THREAD

**Issue by ErikEJ** [ericsink/SQLitePCL.raw#188]
(In a VS extension!) related to #181 

When calling SQLitePCL.Settings.BaseDirectoryForDynamicLoadNativeLibrary I am getting:

```
System.TypeLoadException: Could not load type 'SQLitePCL.Settings' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9c301db686d0bd12'.
   at ReverseEngineer20.EfCoreReverseEngineer.SetFolder()
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\Code\SqlCeToolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 55
```
I am using these SQLite packages

```
  <package id="SQLitePCLRaw.bundle_green" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.core" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.linux" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.osx" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.v110_xp" version="1.1.8" targetFramework="net461" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.net45" version="1.1.8" targetFramework="net461" />

```
What am I doing wrong?

**Comment by ErikEJ** [comment]
Caused by the fact that VS for example Roslyn (and some extensions, incl. Github) use older, pre-release versions of the library, that happended to be loaded iso of the one included with my extension

**Comment by ericsink** [comment]
Sorry I didn't get a reply to this, but I am glad you figured it out.  :-)
