### ISSUE TITLE
Null ref exceptions when disposing sqlite3

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#275]
System.NullReferenceException : Object reference not set to an instance of an object.
   at SQLitePCL.hook_handles.Dispose()
   at SQLitePCL.sqlite3.dispose_extra()
   at SQLitePCL.sqlite3.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation)
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Dispose()
   at Microsoft.Data.Sqlite.SqliteConnection.Close() in C:\Projects\EFCore\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs:line 347
   at Microsoft.Data.Sqlite.SqliteConnection.Dispose(Boolean disposing) in C:\Projects\EFCore\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs:line 364

@bricelam

**Comment by ericsink** [comment]
See aspnet/EntityFrameworkCore#16189

**Comment by bricelam** [comment]
Looks like these come from passing `null` to sqlite3_create_function

**Comment by ericsink** [comment]
Ah, that makes more sense.
