### ISSUE TITLE
Null reference exception when unregistering a collation

### ISSUE THREAD

**Issue by ericsink** [ericsink/SQLitePCL.raw#276]
System.NullReferenceException : Object reference not set to an instance of an object.
   at SQLitePCL.raw.<>c__DisplayClass239_0.<sqlite3_create_collation>b__0(Object ob, ReadOnlySpan`1 s1, ReadOnlySpan`1 s2)
   at SQLitePCL.collation_hook_info.call(ReadOnlySpan`1 s1, ReadOnlySpan`1 s2)
   at SQLitePCL.SQLite3Provider_Cdecl.collation_hook_bridge_impl(IntPtr p, Int32 len1, IntPtr pv1, Int32 len2, IntPtr pv2)
   at SQLitePCL.SQLite3Provider_Cdecl.SQLitePCL.ISQLite3Provider.sqlite3_step(sqlite3_stmt stm)
   at SQLitePCL.raw.sqlite3_step(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult() in C:\Projects\EFCore\src\Microsoft.Data.Sqlite.Core\SqliteDataReader.cs:line 154
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior) in C:\Projects\EFCore\src\Microsoft.Data.Sqlite.Core\SqliteCommand.cs:line 306

@bricelam

**Comment by ericsink** [comment]
See aspnet/EntityFrameworkCore#16189

**Comment by ericsink** [comment]
@bricelam Do you have more context on this?

The fail appears to be happening after the attempted unregister, but it would be helpful to know what the SQL and the circumstances look like.  For example, is this a table with COLLATE on a column?  What SQL statement is executing when the fail happens?

If that's not readily available, no problem, as I'm not stuck.  I can definitely see problems with the relevant code and I am proceeding to address them.

**Comment by bricelam** [comment]
``` csharp
[Fact(Skip = "ericsink/SQLitePCL.raw#276")]
public void CreateCollation_with_null_comparer_works()
{
    using (var connection = new SqliteConnection("Data Source=:memory:"))
    {
        connection.Open();
        connection.CreateCollation("MY_NOCASE", (s1, s2) => string.Compare(s1, s2, StringComparison.OrdinalIgnoreCase));
        connection.CreateCollation("MY_NOCASE", null);

        var ex = Assert.Throws<SqliteException>(
            () => connection.ExecuteScalar<long>("SELECT 'Νικοσ' = 'ΝΙΚΟΣ' COLLATE MY_NOCASE;"));

        Assert.Equal(Resources.SqliteNativeError(SQLITE_ERROR, "no such collation sequence: MY_NOCASE"), ex.Message);
    }
}
```
