### ISSUE TITLE
build failed on Linux Platform

### ISSUE THREAD

**Issue by sunny868** [ericsink/SQLitePCL.raw#359]
I'm not sure if this library can be built on Linux. Then I build it on Linux (unbuntu 16.4 x86-64),but failed . The error info is :

~/SQLitePCL.raw/build$ sudo /home/gysun/dotnet-sdk-2.1.300-linux-x64/dotnet run

Finished dotnet restore in /home/gysun/SQLitePCL.raw/src/providers after 826L milliseconds
-------- t4 -o /home/gysun/SQLitePCL.raw/src/SQLitePCLRaw.provider.dynamic_cdecl/Generated/provider_dynamic_cdecl.cs -p:NAME=dynamic_cdecl -p:CONV=Cdecl -p:KIND=dynamic -p:UWP=false -p:FEATURE_KEY=true  provider.tt in /home/gysun/SQLitePCL.raw/src/providers

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at build.exec(String filename, String args, String startDir) in /home/gysun/SQLitePCL.raw/build/exec.fs:line 27
   at Program.exec@8-10.Invoke(String filename, String args, String startDir) in /home/gysun/SQLitePCL.raw/build/Program.fs:line 8
   at Program.main(String[] argv) in /home/gysun/SQLitePCL.raw/build/Program.fs:line 44

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
I don`t know the reason of failure.

**Comment by sunny868** [comment]
### I had install t4 ,but also error like title info.
$ dotnet tool install -g dotnet-t4
Tools directory '/home/gysun/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/home/gysun/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/home/gysun/.dotnet/tools"

You can invoke the tool using the following command: t4
Tool 'dotnet-t4' (version '2.0.5') was successfully installed
