### ISSUE TITLE
Alpine ARM64 support

### ISSUE THREAD

**Issue by dongle-the-gadget** [ericsink/SQLitePCL.raw#456]
The current binaries don't work in Alpine ARM64 (`linux-musl-arm64`). It would throw the following exception:
```
System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libe_sqlite3: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.Init()
```

**Comment by ericsink** [comment]
I'm confused.  Did you look at #453 ?  It also mentions the need to support musl-arm64.  How is what you are reporting different?  Why is this not a duplicate?

**Comment by malte-v** [comment]
Isn't this fixed now? I'm on Alpine aarch64 and the above error has disappeared after "upgrading" to the latest pre-release from nuget.

**Comment by ericsink** [comment]
@malte-v Yes, I *think* it is fixed, but I hadn't seen confirmation.  Until you just posted your comment.  Thanks.

I'll close this when I release 2.1.0.
