### ISSUE TITLE
e_sqlite2 not found

### ISSUE THREAD

**Issue by DipakTated** [ericsink/SQLitePCL.raw#559]
Exception: Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) C:\DDrive\Work\OneQA\teet\biomedical\src\Local\Fluke.OneQa.Local.Web\bin\Debug\runtimes\win-x64\native\e_sqlite3.dll
    2) C:\DDrive\Work\OneQA\teet\biomedical\src\Local\Fluke.OneQa.Local.Web\bin\Debug\e_sqlite3.dll
win TryLoad: C:\DDrive\Work\OneQA\teet\biomedical\src\Local\Fluke.OneQa.Local.Web\bin\Debug\runtimes\win-x64\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: C:\DDrive\Work\OneQA\teet\biomedical\src\Local\Fluke.OneQa.Local.Web\bin\Debug\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND

Earlier my application was running with x86 version and it was running all fine. I changed my target to x64 bit application and target to x64 and now am facing this problem?

**Comment by DipakTated** [comment]
using these latest versions

![image](https://github.com/ericsink/SQLitePCL.raw/assets/82955638/7f3efe35-89d3-484e-a038-26a267531049)
![image](https://github.com/ericsink/SQLitePCL.raw/assets/82955638/0e5fe18f-9460-4332-85a5-13bc712701cd)

**Comment by pgroene** [comment]
You have to make sure the runtimes\win-x64\native\e_sqlite3.dll directory is copied into your deployment,
