### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'e_sqlcipher' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable

### ISSUE THREAD

**Issue by Neilsons** [ericsink/SQLitePCL.raw#578]
What version of SQLitePCLRaw are you using?

2.1.7

If you are using one of the SQLitePCLRaw bundle packages, which one?
SQLitePCLRaw.bundle_e_sqlcipher 2.1.7

What platform are you running on?  What operating system?  Which version?  What CPU?

Linux  Centos 7   X64

What target framework are you building for?
.Net 7.0

Are you on .NET Framework or the newer stuff (.NET Core, .NET 5+, etc)?

.Net7

Are you using the command line, or an IDE?  Which IDE?  Which version of that IDE?

IDE  17.5.4 

What is the exact error message you are seeing when the problem happens?

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'e_sqlcipher' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/srv/Sdk/e_sqlcipher.so: cannot open shared object file: No such file or directory
/lib64/libc.so.6: version `GLIBC_2.28' not found (required by /srv/Sdk/libe_sqlcipher.so)
libe_sqlcipher.so: cannot open shared object file: No such file or directory
/srv/Sdk/e_sqlcipher: cannot open shared object file: No such file or directory
/srv/Sdk/libe_sqlcipher: cannot open shared object file: No such file or directory

   at SQLitePCL.SQLite3Provider_e_sqlcipher.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlcipher.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()

Are you using `PackageReference` or `packages.config`?

PackageReference

If you are using mobile platforms, are you on classic/legacy Xamarin or on .NET 6 and higher?

No

Sometimes other packages using SQLitePCLRaw cause problems when they are mixed together.  What other packages are you including in your project?
Microsoft.Data.Sqlite.Core  7.0.14
System.Data.SQLite 1.0.118

**Comment by Neilsons** [comment]
[Example](https://github.com/Neilsons/TestSQLitePCLRaw.git)

**Comment by ericsink** [comment]
Initial take:  Looks like something is going wrong with loading the native `e_sqlcipher` shared library, like perhaps it is compiled for a different libc than your system has, or something like that.

**Comment by sjlombardo** [comment]
@ericsink  @Neilsons - Centos 7 uses an ancient version of glibc, I believe 2.17. The library would have to be rebuild against that version or older for it to work.

**Comment by ericsink** [comment]
@sjlombardo Ah, that would explain it.  Thanks for the info.

@Neilsons Sorry, but I do not intend to address this issue.

**Comment by Neilsons** [comment]
@ericsink Thank you very much for your reply, I will try to find other solutions
@sjlombardo Thank you very much for the information

**Comment by Neilsons** [comment]
@ericsink @sjlombardo I tried lowering the version to 2.1.0 and it seems to work. I haven’t tried other versions yet.

**Comment by hgy59** [comment]
This is still an issue on systems having glibc <= 2.26.

.NET 8 (and even .NET 9) runs fine on such systems, but you cannot use `Microsoft.Data.Sqlite`  >= 8.0.4 since it depends on `SQLitePCLRaw.bundle_e_sqlite3 (>= 2.1.6)`

AFAICT the whole dotnet ecosystem runs on linux with glibc 2.26, only the dependeny of SQLitePCLRaw breaks it.

We first identified this issue in https://github.com/SynoCommunity/spksrc/pull/6101#issuecomment-2142086263
but now it popped up in another package https://github.com/SynoCommunity/spksrc/issues/6346

**How can we build SQLitePCLRaw for linux systems having glibc <= 2.26?**

**Comment by hgy59** [comment]
> How can we build SQLitePCLRaw for linux systems having glibc <= 2.26?

To answer my own question:
We found a way to cross compile `libe_sqlite3.so` with older toolchains to get rid of this limitation
see https://github.com/SynoCommunity/spksrc/pull/6348

@Neilsons if you still want to fix this issue, you can compile `libe_sqlite3.so` from sources on your target system. You don't need cross toolchains, you can use a regular build environment with gcc. You can find some hints in the linked PR (compiler flags, required source files).
